parameters:
  - name: branchName
    type: string


jobs:
  - job: CleanupServices
    steps:
      #Cleanup Service Environment - argocd
      - template: dispatch.yml@ci-cd-azure-pipelines
        parameters:
          definitionId: "28"
          sourceBranch: "master"
          inputs: '"branchName": "${{ parameters.branchName }}"'
  - job: CleanupDevEnvironment
    dependsOn: CleanupServices
    steps:
      #Delete Branch Dev Environment <-> dev-environment
      - template: dispatch.yml@ci-cd-azure-pipelines
        parameters:
          definitionId: "31"
          sourceBranch: "master"
          inputs: '"branchName": "${{ parameters.branchName }}"'
