parameters:
  - name: repoName
    type: string
  - name: buildType
    type: string
  - name: branchName
    type: string
  - name: umbrellaChartBaseName
    type: string
  - name: infrastructureBaseBranchName
    type: string
  - name: valueFile
    type: string

jobs:
  - job: CalculateBranchName
    steps:
      - bash: |
          echo "##vso[task.setvariable variable=myBranchName;isoutput=true]$(basename $bn)"
        name: cbn
        env:
          bn: ${{ parameters.branchName }}
  - job: CalculateVersion
    displayName: Calculate Version
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: ServiceRepository
        fetchTags: true
        fetchDepth: 0
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: "5.x"
      - task: gitversion/execute@0
        name: calculateVersion
        displayName: Calculating version
        inputs:
          useConfigFile: True
          configFilePath: "GitVersion.yml"
          additionalArguments: '"/b" "${{ parameters.branchName }}"'
  - job: HelmUmbrellaChartPublish
    dependsOn:
      - CalculateBranchName
      - CalculateVersion
    displayName: "Helm Umbrella Chart Publish"
    variables:
      version: $[dependencies.CalculateVersion.outputs['calculateVersion.GitVersion.SemVer']]
      umbrella-chart-base-branch-name: ${{ parameters.umbrellaChartBaseName }}
      infrastructure-base-branch-name: ${{ parameters.infrastructureBaseBranchName }}
      build-type: ${{ parameters.buildType }}
      branch-name: $[dependencies.CalculateBranchName.outputs['cbn.myBranchName']]
      repo-name: ${{ parameters.repoName }}
      value-file: ${{ parameters.valueFile }}
    steps:
      #Create Branch with Reuse <-> helm-umbrella-chart
      - template: dispatch.yml@ci-cd-azure-pipelines
        parameters:
          definitionId: "22"
          sourceBranch: "$(umbrella-chart-base-branch-name)"
          inputs: '"branchName": "$(build-type)/$(branch-name)-$(repo-name)"'
      #Publish and Prepare Environment <-> helm-umbrella-chartz
      - template: dispatch.yml@ci-cd-azure-pipelines
        parameters:
          definitionId: "35"
          sourceBranch: "$(umbrella-chart-base-branch-name)"
          inputs: '"branchName": "$(build-type)/$(branch-name)", "repoName": "$(repo-name)", "serviceVersion": "$(version)", "umbrellaChartBaseName": "$(umbrella-chart-base-branch-name)"'
      #Build Infrastructure for Environment <-> helm-infrastructure-chart
      - template: dispatch.yml@ci-cd-azure-pipelines
        parameters:
          definitionId: "37"
          sourceBranch: "$(infrastructure-base-branch-name)"
          inputs: '"branchName": "$(build-type)/$(branch-name)-$(repo-name)", "valueFile": "$(value-file)"'
      #Build Service Environment - argocd
      - template: dispatch.yml@ci-cd-azure-pipelines
        parameters:
          definitionId: "38"
          sourceBranch: "master"
          inputs: '"branchName": "$(build-type)/$(branch-name)-$(repo-name)"'
